// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace INTELLISTOCKS_MODELS
{
    public partial class MLModel
    {
        /// <summary>
        /// model input class for MLModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"UserId")]
            public float UserId { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"ID")]
            public float ID { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"Task")]
            public string Task { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"User")]
            public string User { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"Dificuldade")]
            public float Dificuldade { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"UserId")]
            public float UserId { get; set; }

            [ColumnName(@"ID")]
            public float ID { get; set; }

            [ColumnName(@"Task")]
            public float[] Task { get; set; }

            [ColumnName(@"User")]
            public float[] User { get; set; }

            [ColumnName(@"Dificuldade")]
            public float Dificuldade { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

    }
}
